# Generated by Django 3.1.7 on 2021-04-25 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210423_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='cart.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='cart.address'),
        ),
    ]
